config/routes.rb
IMusic::Application.routes.draw do

  

  resources :artists
  resources :albums
  resources :tracks

  match '/search', :controller => :search, :action => :index
  match '/tracks/:id/play', :controller => :tracks, :action => :play, :as => :track_play

  devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  root :controller => :welcome, :action => :index

end

app/models/album.rb
class Album < ActiveRecord::Base

  belongs_to :artist
  has_many :tracks
  
  validates_uniqueness_of :name, :scope => :artist_id

  scope :like, lambda { |query|
    select('albums.*, artists.name as artist_name').
    joins('join artists on artists.id = albums.artist_id').
    where('albums.name LIKE ?', query)
  }

  def name
    self[:name].blank? ? '[unknown]' : self[:name]
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base

  has_many :albums
  has_many :tracks, :through => :album

  validates_uniqueness_of :name  

  scope :like, lambda { |query|
    where('artists.name LIKE ?', query)
  }
  
  def name
    self[:name].blank? ? '[unknown]' : self[:name]
  end

end

app/models/track.rb
class Track < ActiveRecord::Base

  belongs_to :album
  has_one :artist, :through => :album

  validates_uniqueness_of :name, :scope => :album_id

  scope :like, lambda { |query|
    select('tracks.*, artists.name as artist_name').
    joins('join albums on albums.id = tracks.album_id').
    joins('join artists on artists.id = albums.artist_id').
    where('tracks.name LIKE ?', query)
  }

  # Give the playtime in a d:dd format
  def pretty_runtime
    return nil if total_time.nil?
    t = total_time / 1000
    minutes = t / 60
    seconds = t - 60 * minutes
    sprintf '%d:%02d', minutes, seconds
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  # :registerable, :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :load_album, :only => [:show]

  def show
  end

  private

  def load_album
    @album = Album.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :load_artist, :only => [:show]

  def show
  end

  private

  def load_artist
    @artist = Artist.find(params[:id])
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    unless params[:query]
      return false
    end
    query = "%#{params[:query].gsub(/\s/, '%')}%"
    @albums = Album.like(query)
    @tracks = Track.like(query) 
    @artists = Artist.like(query)
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_filter :authenticate_user!
  before_filter :load_track, :only => [:show, :play]

  def show
  end

  def play
    send_file URI.unescape(@track.location.gsub('file://localhost', '')), :type => 'audio/mpeg'
  end

  private

  def load_track
    @track = Track.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_filter :authenticate_user!

  def index
    @artists = Artist.all(:order => 'name asc')
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/show.html.haml
%ul#breadcrumbs
  %li.crumb<>= link_to 'Library', root_path
  %li.crumb<>= link_to @album.artist.name, artist_path(@album.artist)
  %li.crumb<>= @album.name

%ul#things
  - @album.tracks.each do |track|
    %li
      = link_to "&mdash; #{track.name}".html_safe, track_url(track)
      - if track.total_time
        %span.runtime== (#{track.pretty_runtime})

- if @album.tracks.empty?
  %em No tracks

app/views/artists/show.html.haml
%ul#breadcrumbs
  %ul.crumb<>= link_to 'Library', root_url
  %ul.crumb<>= @artist.name

%ul#things 
  - @artist.albums.each do |album|
    %li= link_to "&mdash; #{album.name}".html_safe, album_url(album)

- if @artist.albums.empty?
  %em== No albums for #{@artist.name}

app/views/layouts/application.html.haml
!!! 5

%html

  %head
    %title projectx 
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag

  %body

    #wrapper

      - if notice
        .notice= notice
      - if alert
        .alert= alert

      #top

        #controls
          - if user_signed_in?
            = link_to 'Library', root_url
            = link_to 'Search', search_url
            = link_to 'Logout', destroy_session_path(:user)
          - else
            = link_to 'Login', new_session_path(:user)

        #site_name projectx
        
      = yield

app/views/search/index.html.haml
%ul#breadcrumbs
  %li.crumb= link_to 'Search', search_url
  - if params[:query]
    %li.crumb= params[:query]

%form{:action => search_url, :method => :get}
  %input{:type => 'text', :value => params[:query], :name => 'query'}
  %input{:type => 'submit', :value => 'Search!'}

- if @tracks && @tracks.length != 0
  %h3 Tracks
  %ul.things
    - @tracks.each do |track|
      %li= link_to "&mdash; #{track.name} by #{track.artist_name}".html_safe, track_path(track)

- if @artists && @artists.length != 0
  %h3 Artists
  %ul.things
    - @artists.each do |artist|
      %li= link_to "&mdash; #{artist.name}".html_safe, artist_path(artist)

- if @albums && @albums.length != 0
  %h3 Albums
  %ul.things
    - @albums.each do |album|
      %li= link_to "&mdash; #{album.name} by #{album.artist_name}".html_safe, album_path(album)

app/views/tracks/show.html.haml
%ul#breadcrumbs
  %li.crumb<>= link_to 'Library', root_url
  %li.crumb<>= link_to @track.artist.name, artist_url(@track.artist)
  %li.crumb<>= link_to @track.album.name, album_url(@track.album)
  %li.crumb<>= @track.name

%audio{:src => track_play_url(@track), :controls => 'controls', :autoplay => 'autoplay'}

app/views/welcome/index.html.haml
%ul#breadcrumbs
  %li.crumb.library Library

%ul#things
  - @artists.each do |artist|
    %li= link_to "&mdash; #{artist.name}".html_safe, artist_url(artist)

- if @artists.empty?
  %em No music